# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import timeplus_client
from timeplus_client.api.queries_v1beta2_api import QueriesV1beta2Api  # noqa: E501
from timeplus_client.rest import ApiException


class TestQueriesV1beta2Api(unittest.TestCase):
    """QueriesV1beta2Api unit test stubs"""

    def setUp(self):
        self.api = QueriesV1beta2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1beta2_queries_post(self):
        """Test case for v1beta2_queries_post

        execute a query.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
