# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import timeplus_client
from timeplus_client.models.update_dashboard_request import (
    UpdateDashboardRequest,
)  # noqa: E501
from timeplus_client.rest import ApiException


class TestUpdateDashboardRequest(unittest.TestCase):
    """UpdateDashboardRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateDashboardRequest(self):
        """Test UpdateDashboardRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = timeplus_client.models.update_dashboard_request.UpdateDashboardRequest()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
