# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import timeplus_client
from timeplus_client.api.ud_fs_v1beta1_api import UDFsV1beta1Api  # noqa: E501
from timeplus_client.rest import ApiException


class TestUDFsV1beta1Api(unittest.TestCase):
    """UDFsV1beta1Api unit test stubs"""

    def setUp(self):
        self.api = UDFsV1beta1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1beta1_udfs_get(self):
        """Test case for v1beta1_udfs_get

        list udf.  # noqa: E501
        """
        pass

    def test_v1beta1_udfs_name_delete(self):
        """Test case for v1beta1_udfs_name_delete

        delete a udf.  # noqa: E501
        """
        pass

    def test_v1beta1_udfs_name_get(self):
        """Test case for v1beta1_udfs_name_get

        get a udf.  # noqa: E501
        """
        pass

    def test_v1beta1_udfs_post(self):
        """Test case for v1beta1_udfs_post

        create a udf.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
