# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.query_pipeline_edge import QueryPipelineEdge  # noqa: E501
from swagger_client.rest import ApiException


class TestQueryPipelineEdge(unittest.TestCase):
    """QueryPipelineEdge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryPipelineEdge(self):
        """Test QueryPipelineEdge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.query_pipeline_edge.QueryPipelineEdge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
