# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.timeplus.udfs_v1beta2_api import UDFsV1beta2Api  # noqa: E501
from swagger_client.rest import ApiException


class TestUDFsV1beta2Api(unittest.TestCase):
    """UDFsV1beta2Api unit test stubs"""

    def setUp(self):
        self.api = UDFsV1beta2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1beta2_udfs_get(self):
        """Test case for v1beta2_udfs_get

        list udf.  # noqa: E501
        """
        pass

    def test_v1beta2_udfs_name_delete(self):
        """Test case for v1beta2_udfs_name_delete

        delete a udf.  # noqa: E501
        """
        pass

    def test_v1beta2_udfs_name_get(self):
        """Test case for v1beta2_udfs_name_get

        get a udf.  # noqa: E501
        """
        pass

    def test_v1beta2_udfs_name_put(self):
        """Test case for v1beta2_udfs_name_put

        update a udf.  # noqa: E501
        """
        pass

    def test_v1beta2_udfs_post(self):
        """Test case for v1beta2_udfs_post

        create a udf.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
