# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.timeplus.sources_v1beta1_api import SourcesV1beta1Api  # noqa: E501
from swagger_client.rest import ApiException


class TestSourcesV1beta1Api(unittest.TestCase):
    """SourcesV1beta1Api unit test stubs"""

    def setUp(self):
        self.api = SourcesV1beta1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1beta1_source_infer_post(self):
        """Test case for v1beta1_source_infer_post

        infer schema from an existing event  # noqa: E501
        """
        pass

    def test_v1beta1_source_match_post(self):
        """Test case for v1beta1_source_match_post

        return streams match provided events  # noqa: E501
        """
        pass

    def test_v1beta1_source_preview_post(self):
        """Test case for v1beta1_source_preview_post

        preview a source.  # noqa: E501
        """
        pass

    def test_v1beta1_source_upload_post(self):
        """Test case for v1beta1_source_upload_post

        upload a file  # noqa: E501
        """
        pass

    def test_v1beta1_sources_get(self):
        """Test case for v1beta1_sources_get

        list sources.  # noqa: E501
        """
        pass

    def test_v1beta1_sources_id_delete(self):
        """Test case for v1beta1_sources_id_delete

        delete a source.  # noqa: E501
        """
        pass

    def test_v1beta1_sources_id_get(self):
        """Test case for v1beta1_sources_id_get

        get a source.  # noqa: E501
        """
        pass

    def test_v1beta1_sources_id_put(self):
        """Test case for v1beta1_sources_id_put

        Update a source.  # noqa: E501
        """
        pass

    def test_v1beta1_sources_id_start_post(self):
        """Test case for v1beta1_sources_id_start_post

        start a source.  # noqa: E501
        """
        pass

    def test_v1beta1_sources_id_stop_post(self):
        """Test case for v1beta1_sources_id_stop_post

        stop a source.  # noqa: E501
        """
        pass

    def test_v1beta1_sources_post(self):
        """Test case for v1beta1_sources_post

        create a source.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
