# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.resource_metrics_request import ResourceMetricsRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestResourceMetricsRequest(unittest.TestCase):
    """ResourceMetricsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceMetricsRequest(self):
        """Test ResourceMetricsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.resource_metrics_request.ResourceMetricsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
