# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.event_infer_response import EventInferResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestEventInferResponse(unittest.TestCase):
    """EventInferResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventInferResponse(self):
        """Test EventInferResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.event_infer_response.EventInferResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
