# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.timeplus.misc_api import MiscApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMiscApi(unittest.TestCase):
    """MiscApi unit test stubs"""

    def setUp(self):
        self.api = MiscApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_info_get(self):
        """Test case for info_get

        get the version information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
