# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.timeplus.license_v1beta2_api import LicenseV1beta2Api  # noqa: E501
from swagger_client.rest import ApiException


class TestLicenseV1beta2Api(unittest.TestCase):
    """LicenseV1beta2Api unit test stubs"""

    def setUp(self):
        self.api = LicenseV1beta2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1beta2_licenses_get(self):
        """Test case for v1beta2_licenses_get

        list all lcenses  # noqa: E501
        """
        pass

    def test_v1beta2_licenses_id_delete(self):
        """Test case for v1beta2_licenses_id_delete

        remove a lcense by id  # noqa: E501
        """
        pass

    def test_v1beta2_licenses_id_get(self):
        """Test case for v1beta2_licenses_id_get

        get a lcense by id  # noqa: E501
        """
        pass

    def test_v1beta2_licenses_post(self):
        """Test case for v1beta2_licenses_post

        upload and create a lcense  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
