# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.source_with_metrics import SourceWithMetrics  # noqa: E501
from swagger_client.rest import ApiException


class TestSourceWithMetrics(unittest.TestCase):
    """SourceWithMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceWithMetrics(self):
        """Test SourceWithMetrics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.source_with_metrics.SourceWithMetrics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
