# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.timeplus.invitations_v1beta2_api import InvitationsV1beta2Api  # noqa: E501
from swagger_client.rest import ApiException


class TestInvitationsV1beta2Api(unittest.TestCase):
    """InvitationsV1beta2Api unit test stubs"""

    def setUp(self):
        self.api = InvitationsV1beta2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1beta2_invitations_get(self):
        """Test case for v1beta2_invitations_get

        list invitations  # noqa: E501
        """
        pass

    def test_v1beta2_invitations_id_delete(self):
        """Test case for v1beta2_invitations_id_delete

        delete an invitation  # noqa: E501
        """
        pass

    def test_v1beta2_invitations_post(self):
        """Test case for v1beta2_invitations_post

        create an invitation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
