# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_query_request_v1_beta1 import CreateQueryRequestV1Beta1  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateQueryRequestV1Beta1(unittest.TestCase):
    """CreateQueryRequestV1Beta1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateQueryRequestV1Beta1(self):
        """Test CreateQueryRequestV1Beta1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_query_request_v1_beta1.CreateQueryRequestV1Beta1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
