# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.timeplus.alerts_v1beta2_api import AlertsV1beta2Api  # noqa: E501
from swagger_client.rest import ApiException


class TestAlertsV1beta2Api(unittest.TestCase):
    """AlertsV1beta2Api unit test stubs"""

    def setUp(self):
        self.api = AlertsV1beta2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1beta2_alerts_id_stop_post(self):
        """Test case for v1beta2_alerts_id_stop_post

        stop an alert.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
