# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.timeplus.views_v1beta1_api import ViewsV1beta1Api  # noqa: E501
from swagger_client.rest import ApiException


class TestViewsV1beta1Api(unittest.TestCase):
    """ViewsV1beta1Api unit test stubs"""

    def setUp(self):
        self.api = ViewsV1beta1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1beta1_views_get(self):
        """Test case for v1beta1_views_get

        list views.  # noqa: E501
        """
        pass

    def test_v1beta1_views_name_delete(self):
        """Test case for v1beta1_views_name_delete

        delete a view.  # noqa: E501
        """
        pass

    def test_v1beta1_views_name_patch(self):
        """Test case for v1beta1_views_name_patch

        Update a view.  # noqa: E501
        """
        pass

    def test_v1beta1_views_post(self):
        """Test case for v1beta1_views_post

        create a view.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
