# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConnectionConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auto_create': 'bool',
        'stream_definition': 'StreamDef'
    }

    attribute_map = {
        'auto_create': 'auto_create',
        'stream_definition': 'stream_definition'
    }

    def __init__(self, auto_create=None, stream_definition=None):  # noqa: E501
        """ConnectionConfig - a model defined in Swagger"""  # noqa: E501
        self._auto_create = None
        self._stream_definition = None
        self.discriminator = None
        if auto_create is not None:
            self.auto_create = auto_create
        if stream_definition is not None:
            self.stream_definition = stream_definition

    @property
    def auto_create(self):
        """Gets the auto_create of this ConnectionConfig.  # noqa: E501


        :return: The auto_create of this ConnectionConfig.  # noqa: E501
        :rtype: bool
        """
        return self._auto_create

    @auto_create.setter
    def auto_create(self, auto_create):
        """Sets the auto_create of this ConnectionConfig.


        :param auto_create: The auto_create of this ConnectionConfig.  # noqa: E501
        :type: bool
        """

        self._auto_create = auto_create

    @property
    def stream_definition(self):
        """Gets the stream_definition of this ConnectionConfig.  # noqa: E501


        :return: The stream_definition of this ConnectionConfig.  # noqa: E501
        :rtype: StreamDef
        """
        return self._stream_definition

    @stream_definition.setter
    def stream_definition(self, stream_definition):
        """Sets the stream_definition of this ConnectionConfig.


        :param stream_definition: The stream_definition of this ConnectionConfig.  # noqa: E501
        :type: StreamDef
        """

        self._stream_definition = stream_definition

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectionConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
