# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Connection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'config': 'ConnectionConfig',
        'stat': 'ConnectionStat'
    }

    attribute_map = {
        'config': 'config',
        'stat': 'stat'
    }

    def __init__(self, config=None, stat=None):  # noqa: E501
        """Connection - a model defined in Swagger"""  # noqa: E501
        self._config = None
        self._stat = None
        self.discriminator = None
        if config is not None:
            self.config = config
        self.stat = stat

    @property
    def config(self):
        """Gets the config of this Connection.  # noqa: E501


        :return: The config of this Connection.  # noqa: E501
        :rtype: ConnectionConfig
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this Connection.


        :param config: The config of this Connection.  # noqa: E501
        :type: ConnectionConfig
        """

        self._config = config

    @property
    def stat(self):
        """Gets the stat of this Connection.  # noqa: E501


        :return: The stat of this Connection.  # noqa: E501
        :rtype: ConnectionStat
        """
        return self._stat

    @stat.setter
    def stat(self, stat):
        """Sets the stat of this Connection.


        :param stat: The stat of this Connection.  # noqa: E501
        :type: ConnectionStat
        """
        if stat is None:
            raise ValueError("Invalid value for `stat`, must not be `None`")  # noqa: E501

        self._stat = stat

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Connection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Connection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
