# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateAPIKeyRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'expire_at': 'str',
        'expire_in': 'str',
        'name': 'str'
    }

    attribute_map = {
        'expire_at': 'expire_at',
        'expire_in': 'expire_in',
        'name': 'name'
    }

    def __init__(self, expire_at=None, expire_in=None, name=None):  # noqa: E501
        """CreateAPIKeyRequest - a model defined in Swagger"""  # noqa: E501
        self._expire_at = None
        self._expire_in = None
        self._name = None
        self.discriminator = None
        if expire_at is not None:
            self.expire_at = expire_at
        if expire_in is not None:
            self.expire_in = expire_in
        self.name = name

    @property
    def expire_at(self):
        """Gets the expire_at of this CreateAPIKeyRequest.  # noqa: E501

        define the expiration time of the API key by specifying the exact date time, cannot use with expire_in  # noqa: E501

        :return: The expire_at of this CreateAPIKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._expire_at

    @expire_at.setter
    def expire_at(self, expire_at):
        """Sets the expire_at of this CreateAPIKeyRequest.

        define the expiration time of the API key by specifying the exact date time, cannot use with expire_in  # noqa: E501

        :param expire_at: The expire_at of this CreateAPIKeyRequest.  # noqa: E501
        :type: str
        """

        self._expire_at = expire_at

    @property
    def expire_in(self):
        """Gets the expire_in of this CreateAPIKeyRequest.  # noqa: E501

        define the expiration time of the API key by specifying the amount of time to count from now, cannot use with expire_at  # noqa: E501

        :return: The expire_in of this CreateAPIKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._expire_in

    @expire_in.setter
    def expire_in(self, expire_in):
        """Sets the expire_in of this CreateAPIKeyRequest.

        define the expiration time of the API key by specifying the amount of time to count from now, cannot use with expire_at  # noqa: E501

        :param expire_in: The expire_in of this CreateAPIKeyRequest.  # noqa: E501
        :type: str
        """

        self._expire_in = expire_in

    @property
    def name(self):
        """Gets the name of this CreateAPIKeyRequest.  # noqa: E501

        the name of the API key  # noqa: E501

        :return: The name of this CreateAPIKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateAPIKeyRequest.

        the name of the API key  # noqa: E501

        :param name: The name of this CreateAPIKeyRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateAPIKeyRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateAPIKeyRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
