# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExternalStream(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'columns': 'list[ColumnsResp]',
        'created_at': 'str',
        'created_by': 'Owner',
        'description': 'str',
        'last_updated_at': 'str',
        'last_updated_by': 'Owner',
        'name': 'str',
        'settings': 'list[ExternalStreamSetting]'
    }

    attribute_map = {
        'columns': 'columns',
        'created_at': 'created_at',
        'created_by': 'created_by',
        'description': 'description',
        'last_updated_at': 'last_updated_at',
        'last_updated_by': 'last_updated_by',
        'name': 'name',
        'settings': 'settings'
    }

    def __init__(self, columns=None, created_at=None, created_by=None, description=None, last_updated_at=None, last_updated_by=None, name=None, settings=None):  # noqa: E501
        """ExternalStream - a model defined in Swagger"""  # noqa: E501
        self._columns = None
        self._created_at = None
        self._created_by = None
        self._description = None
        self._last_updated_at = None
        self._last_updated_by = None
        self._name = None
        self._settings = None
        self.discriminator = None
        if columns is not None:
            self.columns = columns
        if created_at is not None:
            self.created_at = created_at
        if created_by is not None:
            self.created_by = created_by
        self.description = description
        if last_updated_at is not None:
            self.last_updated_at = last_updated_at
        if last_updated_by is not None:
            self.last_updated_by = last_updated_by
        self.name = name
        if settings is not None:
            self.settings = settings

    @property
    def columns(self):
        """Gets the columns of this ExternalStream.  # noqa: E501


        :return: The columns of this ExternalStream.  # noqa: E501
        :rtype: list[ColumnsResp]
        """
        return self._columns

    @columns.setter
    def columns(self, columns):
        """Sets the columns of this ExternalStream.


        :param columns: The columns of this ExternalStream.  # noqa: E501
        :type: list[ColumnsResp]
        """

        self._columns = columns

    @property
    def created_at(self):
        """Gets the created_at of this ExternalStream.  # noqa: E501


        :return: The created_at of this ExternalStream.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ExternalStream.


        :param created_at: The created_at of this ExternalStream.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this ExternalStream.  # noqa: E501


        :return: The created_by of this ExternalStream.  # noqa: E501
        :rtype: Owner
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this ExternalStream.


        :param created_by: The created_by of this ExternalStream.  # noqa: E501
        :type: Owner
        """

        self._created_by = created_by

    @property
    def description(self):
        """Gets the description of this ExternalStream.  # noqa: E501


        :return: The description of this ExternalStream.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ExternalStream.


        :param description: The description of this ExternalStream.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def last_updated_at(self):
        """Gets the last_updated_at of this ExternalStream.  # noqa: E501


        :return: The last_updated_at of this ExternalStream.  # noqa: E501
        :rtype: str
        """
        return self._last_updated_at

    @last_updated_at.setter
    def last_updated_at(self, last_updated_at):
        """Sets the last_updated_at of this ExternalStream.


        :param last_updated_at: The last_updated_at of this ExternalStream.  # noqa: E501
        :type: str
        """

        self._last_updated_at = last_updated_at

    @property
    def last_updated_by(self):
        """Gets the last_updated_by of this ExternalStream.  # noqa: E501


        :return: The last_updated_by of this ExternalStream.  # noqa: E501
        :rtype: Owner
        """
        return self._last_updated_by

    @last_updated_by.setter
    def last_updated_by(self, last_updated_by):
        """Sets the last_updated_by of this ExternalStream.


        :param last_updated_by: The last_updated_by of this ExternalStream.  # noqa: E501
        :type: Owner
        """

        self._last_updated_by = last_updated_by

    @property
    def name(self):
        """Gets the name of this ExternalStream.  # noqa: E501


        :return: The name of this ExternalStream.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ExternalStream.


        :param name: The name of this ExternalStream.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def settings(self):
        """Gets the settings of this ExternalStream.  # noqa: E501


        :return: The settings of this ExternalStream.  # noqa: E501
        :rtype: list[ExternalStreamSetting]
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this ExternalStream.


        :param settings: The settings of this ExternalStream.  # noqa: E501
        :type: list[ExternalStreamSetting]
        """

        self._settings = settings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalStream, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalStream):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
