# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QueryPipelineNodeMetric(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'processed_bytes': 'int',
        'processing_time_ns': 'int'
    }

    attribute_map = {
        'processed_bytes': 'processed_bytes',
        'processing_time_ns': 'processing_time_ns'
    }

    def __init__(self, processed_bytes=None, processing_time_ns=None):  # noqa: E501
        """QueryPipelineNodeMetric - a model defined in Swagger"""  # noqa: E501
        self._processed_bytes = None
        self._processing_time_ns = None
        self.discriminator = None
        if processed_bytes is not None:
            self.processed_bytes = processed_bytes
        if processing_time_ns is not None:
            self.processing_time_ns = processing_time_ns

    @property
    def processed_bytes(self):
        """Gets the processed_bytes of this QueryPipelineNodeMetric.  # noqa: E501


        :return: The processed_bytes of this QueryPipelineNodeMetric.  # noqa: E501
        :rtype: int
        """
        return self._processed_bytes

    @processed_bytes.setter
    def processed_bytes(self, processed_bytes):
        """Sets the processed_bytes of this QueryPipelineNodeMetric.


        :param processed_bytes: The processed_bytes of this QueryPipelineNodeMetric.  # noqa: E501
        :type: int
        """

        self._processed_bytes = processed_bytes

    @property
    def processing_time_ns(self):
        """Gets the processing_time_ns of this QueryPipelineNodeMetric.  # noqa: E501


        :return: The processing_time_ns of this QueryPipelineNodeMetric.  # noqa: E501
        :rtype: int
        """
        return self._processing_time_ns

    @processing_time_ns.setter
    def processing_time_ns(self, processing_time_ns):
        """Sets the processing_time_ns of this QueryPipelineNodeMetric.


        :param processing_time_ns: The processing_time_ns of this QueryPipelineNodeMetric.  # noqa: E501
        :type: int
        """

        self._processing_time_ns = processing_time_ns

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QueryPipelineNodeMetric, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QueryPipelineNodeMetric):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
