# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResourceMetricsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'metrics_names': 'list[str]',
        'metrics_types': 'list[str]',
        'resource_ids': 'list[str]',
        'time_range': 'int'
    }

    attribute_map = {
        'metrics_names': 'metricsNames',
        'metrics_types': 'metricsTypes',
        'resource_ids': 'resourceIds',
        'time_range': 'timeRange'
    }

    def __init__(self, metrics_names=None, metrics_types=None, resource_ids=None, time_range=None):  # noqa: E501
        """ResourceMetricsRequest - a model defined in Swagger"""  # noqa: E501
        self._metrics_names = None
        self._metrics_types = None
        self._resource_ids = None
        self._time_range = None
        self.discriminator = None
        if metrics_names is not None:
            self.metrics_names = metrics_names
        if metrics_types is not None:
            self.metrics_types = metrics_types
        if resource_ids is not None:
            self.resource_ids = resource_ids
        if time_range is not None:
            self.time_range = time_range

    @property
    def metrics_names(self):
        """Gets the metrics_names of this ResourceMetricsRequest.  # noqa: E501


        :return: The metrics_names of this ResourceMetricsRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._metrics_names

    @metrics_names.setter
    def metrics_names(self, metrics_names):
        """Sets the metrics_names of this ResourceMetricsRequest.


        :param metrics_names: The metrics_names of this ResourceMetricsRequest.  # noqa: E501
        :type: list[str]
        """

        self._metrics_names = metrics_names

    @property
    def metrics_types(self):
        """Gets the metrics_types of this ResourceMetricsRequest.  # noqa: E501


        :return: The metrics_types of this ResourceMetricsRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._metrics_types

    @metrics_types.setter
    def metrics_types(self, metrics_types):
        """Sets the metrics_types of this ResourceMetricsRequest.


        :param metrics_types: The metrics_types of this ResourceMetricsRequest.  # noqa: E501
        :type: list[str]
        """

        self._metrics_types = metrics_types

    @property
    def resource_ids(self):
        """Gets the resource_ids of this ResourceMetricsRequest.  # noqa: E501


        :return: The resource_ids of this ResourceMetricsRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._resource_ids

    @resource_ids.setter
    def resource_ids(self, resource_ids):
        """Sets the resource_ids of this ResourceMetricsRequest.


        :param resource_ids: The resource_ids of this ResourceMetricsRequest.  # noqa: E501
        :type: list[str]
        """

        self._resource_ids = resource_ids

    @property
    def time_range(self):
        """Gets the time_range of this ResourceMetricsRequest.  # noqa: E501


        :return: The time_range of this ResourceMetricsRequest.  # noqa: E501
        :rtype: int
        """
        return self._time_range

    @time_range.setter
    def time_range(self, time_range):
        """Sets the time_range of this ResourceMetricsRequest.


        :param time_range: The time_range of this ResourceMetricsRequest.  # noqa: E501
        :type: int
        """

        self._time_range = time_range

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResourceMetricsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceMetricsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
