# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SourceMetrics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'failed_write_count': 'int',
        'read_count': 'int',
        'success_write_bytes': 'int',
        'success_write_count': 'int'
    }

    attribute_map = {
        'failed_write_count': 'failed_write_count',
        'read_count': 'read_count',
        'success_write_bytes': 'success_write_bytes',
        'success_write_count': 'success_write_count'
    }

    def __init__(self, failed_write_count=None, read_count=None, success_write_bytes=None, success_write_count=None):  # noqa: E501
        """SourceMetrics - a model defined in Swagger"""  # noqa: E501
        self._failed_write_count = None
        self._read_count = None
        self._success_write_bytes = None
        self._success_write_count = None
        self.discriminator = None
        if failed_write_count is not None:
            self.failed_write_count = failed_write_count
        if read_count is not None:
            self.read_count = read_count
        if success_write_bytes is not None:
            self.success_write_bytes = success_write_bytes
        if success_write_count is not None:
            self.success_write_count = success_write_count

    @property
    def failed_write_count(self):
        """Gets the failed_write_count of this SourceMetrics.  # noqa: E501


        :return: The failed_write_count of this SourceMetrics.  # noqa: E501
        :rtype: int
        """
        return self._failed_write_count

    @failed_write_count.setter
    def failed_write_count(self, failed_write_count):
        """Sets the failed_write_count of this SourceMetrics.


        :param failed_write_count: The failed_write_count of this SourceMetrics.  # noqa: E501
        :type: int
        """

        self._failed_write_count = failed_write_count

    @property
    def read_count(self):
        """Gets the read_count of this SourceMetrics.  # noqa: E501


        :return: The read_count of this SourceMetrics.  # noqa: E501
        :rtype: int
        """
        return self._read_count

    @read_count.setter
    def read_count(self, read_count):
        """Sets the read_count of this SourceMetrics.


        :param read_count: The read_count of this SourceMetrics.  # noqa: E501
        :type: int
        """

        self._read_count = read_count

    @property
    def success_write_bytes(self):
        """Gets the success_write_bytes of this SourceMetrics.  # noqa: E501


        :return: The success_write_bytes of this SourceMetrics.  # noqa: E501
        :rtype: int
        """
        return self._success_write_bytes

    @success_write_bytes.setter
    def success_write_bytes(self, success_write_bytes):
        """Sets the success_write_bytes of this SourceMetrics.


        :param success_write_bytes: The success_write_bytes of this SourceMetrics.  # noqa: E501
        :type: int
        """

        self._success_write_bytes = success_write_bytes

    @property
    def success_write_count(self):
        """Gets the success_write_count of this SourceMetrics.  # noqa: E501


        :return: The success_write_count of this SourceMetrics.  # noqa: E501
        :rtype: int
        """
        return self._success_write_count

    @success_write_count.setter
    def success_write_count(self, success_write_count):
        """Sets the success_write_count of this SourceMetrics.


        :param success_write_count: The success_write_count of this SourceMetrics.  # noqa: E501
        :type: int
        """

        self._success_write_count = success_write_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SourceMetrics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SourceMetrics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
