# coding: utf-8

"""
    Timeplus

    Welcome to the Timeplus HTTP REST API specification.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@timeplus.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SQLAnalyzeColumn(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'column': 'str',
        'column_type': 'str',
        'database': 'str',
        'is_view': 'bool',
        'table': 'str'
    }

    attribute_map = {
        'column': 'column',
        'column_type': 'column_type',
        'database': 'database',
        'is_view': 'is_view',
        'table': 'table'
    }

    def __init__(self, column=None, column_type=None, database=None, is_view=None, table=None):  # noqa: E501
        """SQLAnalyzeColumn - a model defined in Swagger"""  # noqa: E501
        self._column = None
        self._column_type = None
        self._database = None
        self._is_view = None
        self._table = None
        self.discriminator = None
        if column is not None:
            self.column = column
        if column_type is not None:
            self.column_type = column_type
        if database is not None:
            self.database = database
        if is_view is not None:
            self.is_view = is_view
        if table is not None:
            self.table = table

    @property
    def column(self):
        """Gets the column of this SQLAnalyzeColumn.  # noqa: E501


        :return: The column of this SQLAnalyzeColumn.  # noqa: E501
        :rtype: str
        """
        return self._column

    @column.setter
    def column(self, column):
        """Sets the column of this SQLAnalyzeColumn.


        :param column: The column of this SQLAnalyzeColumn.  # noqa: E501
        :type: str
        """

        self._column = column

    @property
    def column_type(self):
        """Gets the column_type of this SQLAnalyzeColumn.  # noqa: E501


        :return: The column_type of this SQLAnalyzeColumn.  # noqa: E501
        :rtype: str
        """
        return self._column_type

    @column_type.setter
    def column_type(self, column_type):
        """Sets the column_type of this SQLAnalyzeColumn.


        :param column_type: The column_type of this SQLAnalyzeColumn.  # noqa: E501
        :type: str
        """

        self._column_type = column_type

    @property
    def database(self):
        """Gets the database of this SQLAnalyzeColumn.  # noqa: E501


        :return: The database of this SQLAnalyzeColumn.  # noqa: E501
        :rtype: str
        """
        return self._database

    @database.setter
    def database(self, database):
        """Sets the database of this SQLAnalyzeColumn.


        :param database: The database of this SQLAnalyzeColumn.  # noqa: E501
        :type: str
        """

        self._database = database

    @property
    def is_view(self):
        """Gets the is_view of this SQLAnalyzeColumn.  # noqa: E501


        :return: The is_view of this SQLAnalyzeColumn.  # noqa: E501
        :rtype: bool
        """
        return self._is_view

    @is_view.setter
    def is_view(self, is_view):
        """Sets the is_view of this SQLAnalyzeColumn.


        :param is_view: The is_view of this SQLAnalyzeColumn.  # noqa: E501
        :type: bool
        """

        self._is_view = is_view

    @property
    def table(self):
        """Gets the table of this SQLAnalyzeColumn.  # noqa: E501


        :return: The table of this SQLAnalyzeColumn.  # noqa: E501
        :rtype: str
        """
        return self._table

    @table.setter
    def table(self, table):
        """Sets the table of this SQLAnalyzeColumn.


        :param table: The table of this SQLAnalyzeColumn.  # noqa: E501
        :type: str
        """

        self._table = table

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SQLAnalyzeColumn, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SQLAnalyzeColumn):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
